version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-python
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Bangkok
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./doc:/doc   # โฟลเดอร์สำหรับไฟล์ PDF ที่จะ OCR
    restart: unless-stopped
